// Glossaire hors-ligne : prothèse dentaire (FR → PL) et darija de classe (→ PL).
// Darija en écriture latine « marocaine » : 3 = ع, 7 = ح, 9 = ق, kh = polskie „ch”,
// gh = francuskie „r”, ch = „sz”.

export const DENTAL = [
  // Métier & types de prothèses
  { fr: "prothèse dentaire", pl: "proteza zębowa", cat: "Protezy" },
  { fr: "prothésiste dentaire", pl: "technik dentystyczny", cat: "Protezy" },
  { fr: "prothèse fixe (conjointe)", pl: "proteza stała", cat: "Protezy" },
  { fr: "prothèse amovible (adjointe)", pl: "proteza ruchoma (wyjmowana)", cat: "Protezy" },
  { fr: "prothèse adjointe totale (PAT)", pl: "proteza całkowita", cat: "Protezy" },
  { fr: "prothèse adjointe partielle (PAP)", pl: "proteza częściowa", cat: "Protezy" },
  { fr: "stellite / châssis métallique", pl: "proteza szkieletowa (szkielet metalowy)", cat: "Protezy" },
  { fr: "couronne", pl: "korona", cat: "Protezy" },
  { fr: "couronne céramo-métallique (CCM)", pl: "korona metalowo-ceramiczna", cat: "Protezy" },
  { fr: "couronne tout céramique", pl: "korona pełnoceramiczna", cat: "Protezy" },
  { fr: "couronne provisoire", pl: "korona tymczasowa", cat: "Protezy" },
  { fr: "bridge", pl: "most", cat: "Protezy" },
  { fr: "pilier (de bridge)", pl: "filar (mostu)", cat: "Protezy" },
  { fr: "intermédiaire de bridge (pontic)", pl: "przęsło", cat: "Protezy" },
  { fr: "inlay / onlay", pl: "wkład koronowy (inlay / onlay)", cat: "Protezy" },
  { fr: "inlay-core / faux moignon", pl: "wkład koronowo-korzeniowy", cat: "Protezy" },
  { fr: "facette", pl: "licówka", cat: "Protezy" },
  { fr: "implant", pl: "implant", cat: "Protezy" },
  { fr: "pilier implantaire", pl: "łącznik implantologiczny", cat: "Protezy" },
  { fr: "crochet", pl: "klamra", cat: "Protezy" },
  { fr: "attachement", pl: "zasuwa / zatrzask (element precyzyjny)", cat: "Protezy" },
  { fr: "gouttière", pl: "szyna", cat: "Protezy" },
  { fr: "rebasage", pl: "podścielenie protezy", cat: "Protezy" },
  { fr: "réparation", pl: "naprawa", cat: "Protezy" },
  { fr: "appareil orthodontique", pl: "aparat ortodontyczny", cat: "Protezy" },

  // Empreintes & modèles
  { fr: "empreinte", pl: "wycisk", cat: "Wyciski i modele" },
  { fr: "porte-empreinte", pl: "łyżka wyciskowa", cat: "Wyciski i modele" },
  { fr: "porte-empreinte individuel (PEI)", pl: "łyżka indywidualna", cat: "Wyciski i modele" },
  { fr: "alginate", pl: "alginat", cat: "Wyciski i modele" },
  { fr: "silicone", pl: "masa silikonowa", cat: "Wyciski i modele" },
  { fr: "plâtre", pl: "gips", cat: "Wyciski i modele" },
  { fr: "plâtre dur / extra-dur", pl: "gips twardy / supertwardy (klasa III / IV)", cat: "Wyciski i modele" },
  { fr: "couler l'empreinte", pl: "odlać wycisk (gipsem)", cat: "Wyciski i modele" },
  { fr: "modèle (en plâtre)", pl: "model gipsowy", cat: "Wyciski i modele" },
  { fr: "modèle de travail", pl: "model roboczy", cat: "Wyciski i modele" },
  { fr: "modèle antagoniste", pl: "model przeciwstawny", cat: "Wyciski i modele" },
  { fr: "MPU (modèle positif unitaire) / die", pl: "słupek (model dzielony)", cat: "Wyciski i modele" },
  { fr: "socle", pl: "cokół", cat: "Wyciski i modele" },
  { fr: "taille-plâtre", pl: "trymer (do gipsu)", cat: "Wyciski i modele" },
  { fr: "bol et spatule", pl: "miska gumowa i szpatułka", cat: "Wyciski i modele" },
  { fr: "vibreur", pl: "stolik wibracyjny", cat: "Wyciski i modele" },
  { fr: "rapport eau / poudre", pl: "proporcja woda / proszek", cat: "Wyciski i modele" },
  { fr: "temps de prise", pl: "czas wiązania", cat: "Wyciski i modele" },
  { fr: "isolant", pl: "izolator (środek izolujący)", cat: "Wyciski i modele" },
  { fr: "vernis espaceur", pl: "lakier dystansowy", cat: "Wyciski i modele" },

  // Occlusion
  { fr: "occlusion", pl: "zgryz / okluzja", cat: "Zgryz" },
  { fr: "articulé (dentaire)", pl: "zwarcie", cat: "Zgryz" },
  { fr: "articulateur", pl: "artykulator", cat: "Zgryz" },
  { fr: "occluseur", pl: "okludator", cat: "Zgryz" },
  { fr: "arc facial", pl: "łuk twarzowy", cat: "Zgryz" },
  { fr: "maquette d'occlusion", pl: "wzornik zwarciowy", cat: "Zgryz" },
  { fr: "bourrelet (de cire)", pl: "wał zwarciowy (woskowy)", cat: "Zgryz" },
  { fr: "plaque base", pl: "płyta podstawowa", cat: "Zgryz" },
  { fr: "dimension verticale (DVO)", pl: "wymiar pionowy (zwarcia)", cat: "Zgryz" },
  { fr: "relation centrée", pl: "relacja centralna", cat: "Zgryz" },
  { fr: "plan d'occlusion", pl: "płaszczyzna zgryzowa", cat: "Zgryz" },
  { fr: "montage des dents", pl: "ustawianie zębów", cat: "Zgryz" },
  { fr: "dents artificielles / dents du commerce", pl: "zęby sztuczne (fabryczne)", cat: "Zgryz" },
  { fr: "teinte", pl: "kolor / odcień", cat: "Zgryz" },
  { fr: "teintier", pl: "kolornik", cat: "Zgryz" },

  // Anatomie
  { fr: "dent / dents", pl: "ząb / zęby", cat: "Anatomia" },
  { fr: "incisive", pl: "siekacz", cat: "Anatomia" },
  { fr: "canine", pl: "kieł", cat: "Anatomia" },
  { fr: "prémolaire", pl: "ząb przedtrzonowy", cat: "Anatomia" },
  { fr: "molaire", pl: "ząb trzonowy", cat: "Anatomia" },
  { fr: "dent de sagesse", pl: "ząb mądrości", cat: "Anatomia" },
  { fr: "arcade dentaire", pl: "łuk zębowy", cat: "Anatomia" },
  { fr: "maxillaire", pl: "szczęka (górna)", cat: "Anatomia" },
  { fr: "mandibule", pl: "żuchwa", cat: "Anatomia" },
  { fr: "édenté / édentement", pl: "bezzębny / brak zębów (bezzębie)", cat: "Anatomia" },
  { fr: "crête (alvéolaire)", pl: "wyrostek zębodołowy (grzbiet)", cat: "Anatomia" },
  { fr: "gencive", pl: "dziąsło", cat: "Anatomia" },
  { fr: "palais", pl: "podniebienie", cat: "Anatomia" },
  { fr: "langue", pl: "język", cat: "Anatomia" },
  { fr: "couronne (anatomique)", pl: "korona zęba", cat: "Anatomia" },
  { fr: "collet", pl: "szyjka zęba", cat: "Anatomia" },
  { fr: "racine", pl: "korzeń", cat: "Anatomia" },
  { fr: "émail", pl: "szkliwo", cat: "Anatomia" },
  { fr: "dentine", pl: "zębina", cat: "Anatomia" },
  { fr: "pulpe", pl: "miazga", cat: "Anatomia" },
  { fr: "cuspide", pl: "guzek", cat: "Anatomia" },
  { fr: "sillon", pl: "bruzda", cat: "Anatomia" },
  { fr: "face occlusale", pl: "powierzchnia żująca (okluzyjna)", cat: "Anatomia" },
  { fr: "face vestibulaire", pl: "powierzchnia przedsionkowa", cat: "Anatomia" },
  { fr: "face linguale", pl: "powierzchnia językowa", cat: "Anatomia" },
  { fr: "face palatine", pl: "powierzchnia podniebienna", cat: "Anatomia" },
  { fr: "mésial", pl: "przyśrodkowy (mezjalny)", cat: "Anatomia" },
  { fr: "distal", pl: "odśrodkowy (dystalny)", cat: "Anatomia" },
  { fr: "point de contact", pl: "punkt styczny", cat: "Anatomia" },
  { fr: "moignon / dent préparée", pl: "kikut (opracowany ząb)", cat: "Anatomia" },
  { fr: "limite cervicale", pl: "granica preparacji", cat: "Anatomia" },
  { fr: "épaulement / congé", pl: "stopień / żłobek (preparacji)", cat: "Anatomia" },
  { fr: "dépouille", pl: "zbieżność ścian (kąt preparacji)", cat: "Anatomia" },
  { fr: "contre-dépouille", pl: "podcień", cat: "Anatomia" },

  // Matériaux
  { fr: "cire", pl: "wosk", cat: "Materiały" },
  { fr: "cire de modelage", pl: "wosk modelowy", cat: "Materiały" },
  { fr: "maquette en cire / wax-up", pl: "model woskowy (wax-up)", cat: "Materiały" },
  { fr: "résine (acrylique)", pl: "akryl / żywica akrylowa", cat: "Materiały" },
  { fr: "résine autopolymérisable", pl: "akryl samopolimeryzujący", cat: "Materiały" },
  { fr: "résine thermopolymérisable", pl: "akryl termopolimeryzujący (na gorąco)", cat: "Materiały" },
  { fr: "polymérisation", pl: "polimeryzacja", cat: "Materiały" },
  { fr: "céramique", pl: "ceramika (porcelana)", cat: "Materiały" },
  { fr: "zircone", pl: "tlenek cyrkonu (cyrkon)", cat: "Materiały" },
  { fr: "disilicate de lithium", pl: "dwukrzemian litu", cat: "Materiały" },
  { fr: "alliage", pl: "stop (metali)", cat: "Materiały" },
  { fr: "chrome-cobalt (Cr-Co)", pl: "stop chromowo-kobaltowy", cat: "Materiały" },
  { fr: "nickel-chrome (Ni-Cr)", pl: "stop niklowo-chromowy", cat: "Materiały" },
  { fr: "alliage précieux", pl: "stop szlachetny", cat: "Materiały" },
  { fr: "titane", pl: "tytan", cat: "Materiały" },
  { fr: "revêtement", pl: "masa osłaniająca", cat: "Materiały" },
  { fr: "opaque", pl: "opaker", cat: "Materiały" },
  { fr: "dentine / émail (céramique)", pl: "masa zębinowa / szkliwna", cat: "Materiały" },
  { fr: "glaçage", pl: "glazura (glazurowanie)", cat: "Materiały" },
  { fr: "maquillant", pl: "farbki (charakteryzacja)", cat: "Materiały" },

  // Techniques & équipement
  { fr: "modelage", pl: "modelowanie", cat: "Technika" },
  { fr: "mise en revêtement", pl: "osłanianie (zatapianie w masie)", cat: "Technika" },
  { fr: "cylindre", pl: "pierścień odlewniczy (mufla)", cat: "Technika" },
  { fr: "tige de coulée", pl: "kanał wlewowy (trzpień)", cat: "Technika" },
  { fr: "coulée / couler (métal)", pl: "odlew / odlewanie", cat: "Technika" },
  { fr: "fonte / fondre", pl: "topienie / topić", cat: "Technika" },
  { fr: "four (de cuisson)", pl: "piec (do wypalania)", cat: "Technika" },
  { fr: "cuisson", pl: "wypalanie", cat: "Technika" },
  { fr: "four de préchauffage", pl: "piec do wygrzewania", cat: "Technika" },
  { fr: "moufle", pl: "puszka (kiweta)", cat: "Technika" },
  { fr: "mise en moufle", pl: "puszkowanie", cat: "Technika" },
  { fr: "démoulage / démouflage", pl: "wyjmowanie z puszki", cat: "Technika" },
  { fr: "dégrossir", pl: "wstępne opracowanie", cat: "Technika" },
  { fr: "finition", pl: "wykończenie", cat: "Technika" },
  { fr: "polissage", pl: "polerowanie", cat: "Technika" },
  { fr: "fraise", pl: "frez", cat: "Technika" },
  { fr: "pièce à main", pl: "prostnica / mikrosilnik", cat: "Technika" },
  { fr: "sableuse", pl: "piaskarka", cat: "Technika" },
  { fr: "polisseuse / tour à polir", pl: "polerka", cat: "Technika" },
  { fr: "couteau à cire", pl: "nóż do wosku", cat: "Technika" },
  { fr: "bec Bunsen", pl: "palnik (Bunsena)", cat: "Technika" },
  { fr: "spatule", pl: "szpatułka", cat: "Technika" },
  { fr: "pinceau", pl: "pędzelek", cat: "Technika" },
  { fr: "paralléliseur", pl: "paralelometr", cat: "Technika" },
  { fr: "axe d'insertion", pl: "tor wprowadzenia", cat: "Technika" },
  { fr: "rétention", pl: "retencja (utrzymanie)", cat: "Technika" },
  { fr: "stabilisation", pl: "stabilizacja", cat: "Technika" },
  { fr: "sustentation", pl: "podparcie", cat: "Technika" },
  { fr: "CFAO (CAD/CAM)", pl: "CAD/CAM (projektowanie i frezowanie komputerowe)", cat: "Technika" },
  { fr: "scanner (intra-oral / de laboratoire)", pl: "skaner (wewnątrzustny / laboratoryjny)", cat: "Technika" },
  { fr: "usineuse / fraiseuse", pl: "frezarka", cat: "Technika" },
  { fr: "impression 3D", pl: "druk 3D", cat: "Technika" },
  { fr: "désinfection", pl: "dezynfekcja", cat: "Technika" },
  { fr: "le labo / laboratoire", pl: "pracownia (laboratorium) protetyczna", cat: "Technika" },
  { fr: "le praticien / le dentiste", pl: "lekarz dentysta", cat: "Technika" },
  { fr: "fiche de laboratoire", pl: "zlecenie laboratoryjne", cat: "Technika" },
];

export const DARIJA = [
  // Questions & mots outils
  { dj: "daba", ar: "دابا", pl: "teraz", cat: "Słowa klucze" },
  { dj: "dyal / d", ar: "ديال", pl: "„od”, należący do (dzierżawczy): l-empreinte dyal l-mandibule = wycisk żuchwy", cat: "Słowa klucze" },
  { dj: "had / hadi / hada", ar: "هاد", pl: "ten / ta / to", cat: "Słowa klucze" },
  { dj: "hadchi", ar: "هادشي", pl: "to (wszystko), te rzeczy", cat: "Słowa klucze" },
  { dj: "kayn / kayna", ar: "كاين", pl: "jest, istnieje", cat: "Słowa klucze" },
  { dj: "makaynch", ar: "ماكاينش", pl: "nie ma", cat: "Słowa klucze" },
  { dj: "khass / khassek / khasskom", ar: "خاص", pl: "trzeba / musisz / musicie", cat: "Słowa klucze" },
  { dj: "makhassch", ar: "ماخاصش", pl: "nie trzeba / nie wolno", cat: "Słowa klucze" },
  { dj: "ma ... ch", ar: "ما...ش", pl: "przeczenie wokół czasownika: ma-fhmt-ch = nie zrozumiałam", cat: "Słowa klucze" },
  { dj: "bach", ar: "باش", pl: "żeby, aby", cat: "Słowa klucze" },
  { dj: "7it / 7itach", ar: "حيت", pl: "bo, ponieważ", cat: "Słowa klucze" },
  { dj: "ila", ar: "إلا", pl: "jeśli", cat: "Słowa klucze" },
  { dj: "walakin", ar: "ولكن", pl: "ale", cat: "Słowa klucze" },
  { dj: "w", ar: "و", pl: "i", cat: "Słowa klucze" },
  { dj: "wla / ola", ar: "ولا", pl: "albo, czy", cat: "Słowa klucze" },
  { dj: "m3a", ar: "مع", pl: "z (razem z)", cat: "Słowa klucze" },
  { dj: "bla", ar: "بلا", pl: "bez", cat: "Słowa klucze" },
  { dj: "f / fi", ar: "ف", pl: "w", cat: "Słowa klucze" },
  { dj: "3la", ar: "على", pl: "na, o", cat: "Słowa klucze" },
  { dj: "mn", ar: "من", pl: "z, od", cat: "Słowa klucze" },
  { dj: "l / li", ar: "ل", pl: "do, dla", cat: "Słowa klucze" },
  { dj: "bzzaf", ar: "بزاف", pl: "dużo, bardzo, za dużo", cat: "Słowa klucze" },
  { dj: "chwiya", ar: "شوية", pl: "trochę", cat: "Słowa klucze" },
  { dj: "b chwiya", ar: "بشوية", pl: "powoli, ostrożnie", cat: "Słowa klucze" },
  { dj: "dghya / bzerba", ar: "دغيا / بالزربة", pl: "szybko", cat: "Słowa klucze" },
  { dj: "kolchi", ar: "كلشي", pl: "wszystko", cat: "Słowa klucze" },
  { dj: "walou", ar: "والو", pl: "nic", cat: "Słowa klucze" },
  { dj: "hna", ar: "هنا", pl: "tutaj", cat: "Słowa klucze" },
  { dj: "temma / lhih", ar: "تما / لهيه", pl: "tam", cat: "Słowa klucze" },
  { dj: "kifach", ar: "كيفاش", pl: "jak?", cat: "Pytania" },
  { dj: "3lach", ar: "علاش", pl: "dlaczego?", cat: "Pytania" },
  { dj: "chno / ach", ar: "شنو / آش", pl: "co?", cat: "Pytania" },
  { dj: "fin", ar: "فين", pl: "gdzie?", cat: "Pytania" },
  { dj: "imta", ar: "إمتى", pl: "kiedy?", cat: "Pytania" },
  { dj: "chkoun", ar: "شكون", pl: "kto?", cat: "Pytania" },
  { dj: "chhal", ar: "شحال", pl: "ile?", cat: "Pytania" },
  { dj: "wach", ar: "واش", pl: "czy? (rozpoczyna pytanie tak/nie)", cat: "Pytania" },

  // Ce que dit le prof
  { dj: "chouf / choufou", ar: "شوف / شوفو", pl: "patrz / patrzcie", cat: "Polecenia nauczyciela" },
  { dj: "sme3 / sem3ou", ar: "سمع / سمعو", pl: "słuchaj / słuchajcie", cat: "Polecenia nauczyciela" },
  { dj: "fhemti? / fhemtou?", ar: "فهمتي؟ / فهمتو؟", pl: "rozumiesz? / rozumiecie?", cat: "Polecenia nauczyciela" },
  { dj: "dir / diri / diro", ar: "دير / ديري / ديرو", pl: "zrób, połóż (do mężczyzny / kobiety / do grupy)", cat: "Polecenia nauczyciela" },
  { dj: "3tini", ar: "عطيني", pl: "daj mi", cat: "Polecenia nauczyciela" },
  { dj: "jib / jibi", ar: "جيب", pl: "przynieś", cat: "Polecenia nauczyciela" },
  { dj: "khoud / khoudi", ar: "خود", pl: "weź", cat: "Polecenia nauczyciela" },
  { dj: "3awd", ar: "عاود", pl: "powtórz, jeszcze raz", cat: "Polecenia nauczyciela" },
  { dj: "kteb / ketbou", ar: "كتب", pl: "pisz / piszcie", cat: "Polecenia nauczyciela" },
  { dj: "gles / glsou", ar: "گلس", pl: "usiądź / usiądźcie", cat: "Polecenia nauczyciela" },
  { dj: "noud", ar: "نوض", pl: "wstań", cat: "Polecenia nauczyciela" },
  { dj: "sir / siri", ar: "سير", pl: "idź", cat: "Polecenia nauczyciela" },
  { dj: "aji / ajiw", ar: "أجي / أجيو", pl: "chodź / chodźcie tu", cat: "Polecenia nauczyciela" },
  { dj: "tsenna", ar: "تسنى", pl: "poczekaj", cat: "Polecenia nauczyciela" },
  { dj: "rd balek", ar: "رد بالك", pl: "uważaj!", cat: "Polecenia nauczyciela" },
  { dj: "safi", ar: "صافي", pl: "wystarczy / gotowe / ok", cat: "Polecenia nauczyciela" },
  { dj: "yallah", ar: "يالله", pl: "dalej, zaczynamy", cat: "Polecenia nauczyciela" },
  { dj: "wakha", ar: "واخا", pl: "dobrze, ok", cat: "Polecenia nauczyciela" },
  { dj: "mzyan", ar: "مزيان", pl: "dobrze, ładnie", cat: "Polecenia nauczyciela" },
  { dj: "machi mzyan / khayb", ar: "ماشي مزيان / خايب", pl: "niedobrze, brzydko", cat: "Polecenia nauczyciela" },
  { dj: "machi", ar: "ماشي", pl: "nie (to nie jest...)", cat: "Polecenia nauczyciela" },
  { dj: "bhal bhal", ar: "بحال بحال", pl: "tak samo", cat: "Polecenia nauczyciela" },
  { dj: "bhal", ar: "بحال", pl: "jak, podobnie do", cat: "Polecenia nauczyciela" },

  // Gestes du labo
  { dj: "khellet", ar: "خلط", pl: "wymieszaj", cat: "W pracowni" },
  { dj: "sebb / kebb", ar: "صب / كب", pl: "wlej, wylej", cat: "W pracowni" },
  { dj: "qte3", ar: "قطع", pl: "tnij, odetnij", cat: "W pracowni" },
  { dj: "7ekk", ar: "حك", pl: "szlifuj, pocieraj", cat: "W pracowni" },
  { dj: "seddu / 7ell", ar: "سد / حل", pl: "zamknij / otwórz", cat: "W pracowni" },
  { dj: "nchef / yabes", ar: "نشف / يابس", pl: "wysusz / suchy", cat: "W pracowni" },
  { dj: "fazeg", ar: "فازگ", pl: "mokry", cat: "W pracowni" },
  { dj: "lma", ar: "الما", pl: "woda", cat: "W pracowni" },
  { dj: "l-3afya / nar", ar: "العافية / النار", pl: "ogień, płomień", cat: "W pracowni" },
  { dj: "sakhen / s5oun", ar: "سخون", pl: "gorący", cat: "W pracowni" },
  { dj: "bared", ar: "بارد", pl: "zimny", cat: "W pracowni" },
  { dj: "kbir / sghir", ar: "كبير / صغير", pl: "duży / mały", cat: "W pracowni" },
  { dj: "twil / qsir", ar: "طويل / قصير", pl: "długi / krótki", cat: "W pracowni" },
  { dj: "r9i9 / ghlid", ar: "رقيق / غليظ", pl: "cienki / gruby", cat: "W pracowni" },
  { dj: "qaseh / rteb", ar: "قاصح / رطب", pl: "twardy / miękki", cat: "W pracowni" },
  { dj: "sna / snan", ar: "سنة / سنان", pl: "ząb / zęby", cat: "W pracowni" },
  { dj: "dersa / drass", ar: "ضرسة / ضراس", pl: "ząb trzonowy / trzonowce", cat: "W pracowni" },
  { dj: "nab", ar: "ناب", pl: "kieł", cat: "W pracowni" },
  { dj: "fomm", ar: "فم", pl: "usta", cat: "W pracowni" },
  { dj: "lsan", ar: "لسان", pl: "język", cat: "W pracowni" },
  { dj: "l-ltha", ar: "اللثة", pl: "dziąsło", cat: "W pracowni" },
  { dj: "l-7nak", ar: "الحنك", pl: "szczęka / żuchwa", cat: "W pracowni" },
  { dj: "l-fouq / l-te7t", ar: "الفوق / التحت", pl: "górny / dolny", cat: "W pracowni" },
  { dj: "l-limn / l-lissr", ar: "اليمن / اليسر", pl: "prawy / lewy", cat: "W pracowni" },
  { dj: "l-qdam / l-lour", ar: "القدام / اللور", pl: "przód / tył", cat: "W pracowni" },

  // Temps & école
  { dj: "lyoum", ar: "اليوم", pl: "dzisiaj", cat: "Czas i szkoła" },
  { dj: "ghedda", ar: "غدا", pl: "jutro", cat: "Czas i szkoła" },
  { dj: "lbare7", ar: "البارح", pl: "wczoraj", cat: "Czas i szkoła" },
  { dj: "dqiqa", ar: "دقيقة", pl: "minuta", cat: "Czas i szkoła" },
  { dj: "sa3a", ar: "ساعة", pl: "godzina", cat: "Czas i szkoła" },
  { dj: "l-imti7an / l-examen", ar: "الامتحان", pl: "egzamin", cat: "Czas i szkoła" },
  { dj: "t-tamrin", ar: "التمرين", pl: "ćwiczenie", cat: "Czas i szkoła" },
  { dj: "l-khedma", ar: "الخدمة", pl: "praca", cat: "Czas i szkoła" },
  { dj: "l-ostad / l-ostada", ar: "الأستاذ", pl: "nauczyciel / nauczycielka", cat: "Czas i szkoła" },
  { dj: "t-talib / t-talaba", ar: "الطالب", pl: "student / studenci", cat: "Czas i szkoła" },

  // Pour elle
  { dj: "3afak", ar: "عافاك", pl: "proszę (o coś)", cat: "Dla Ciebie" },
  { dj: "choukran", ar: "شكرا", pl: "dziękuję", cat: "Dla Ciebie" },
  { dj: "smeh liya", ar: "سمح ليا", pl: "przepraszam", cat: "Dla Ciebie" },
  { dj: "ma fhemtch", ar: "ما فهمتش", pl: "nie zrozumiałam", cat: "Dla Ciebie" },
  { dj: "3awd 3afak", ar: "عاود عافاك", pl: "powtórz, proszę", cat: "Dla Ciebie" },
  { dj: "b chwiya 3afak", ar: "بشوية عافاك", pl: "wolniej, proszę", cat: "Dla Ciebie" },
  { dj: "goulha b l-français 3afak", ar: "گولها بالفرنسية عافاك", pl: "powiedz to po francusku, proszę", cat: "Dla Ciebie" },
  { dj: "ana polonia / ana mn Polonia", ar: "أنا من بولونيا", pl: "jestem z Polski", cat: "Dla Ciebie" },
  { dj: "iyeh / ah", ar: "إيه / آه", pl: "tak", cat: "Dla Ciebie" },
  { dj: "la", ar: "لا", pl: "nie", cat: "Dla Ciebie" },

  // Chiffres
  { dj: "wa7ed", ar: "واحد", pl: "1", cat: "Liczby" },
  { dj: "jouj", ar: "جوج", pl: "2", cat: "Liczby" },
  { dj: "tlata", ar: "تلاتة", pl: "3", cat: "Liczby" },
  { dj: "reb3a", ar: "ربعة", pl: "4", cat: "Liczby" },
  { dj: "khamsa", ar: "خمسة", pl: "5", cat: "Liczby" },
  { dj: "stta", ar: "ستة", pl: "6", cat: "Liczby" },
  { dj: "seb3a", ar: "سبعة", pl: "7", cat: "Liczby" },
  { dj: "tmnya", ar: "تمنية", pl: "8", cat: "Liczby" },
  { dj: "tes3oud", ar: "تسعود", pl: "9", cat: "Liczby" },
  { dj: "3achra", ar: "عشرة", pl: "10", cat: "Liczby" },
  { dj: "3echrin", ar: "عشرين", pl: "20", cat: "Liczby" },
  { dj: "nos", ar: "نص", pl: "pół, połowa", cat: "Liczby" },
  { dj: "rbe3", ar: "ربع", pl: "ćwierć", cat: "Liczby" },
  { dj: "mya", ar: "مية", pl: "100", cat: "Liczby" },
];

// ---------- Détection des termes du glossaire dans un texte reconnu ----------

const norm = (s) => s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[’']/g, " ");
const ARTICLES = /\b(le|la|les|l|un|une|de|du|des|d)\b/g;
const words = (s) => " " + norm(s).replace(/[^\p{L}\p{N}]+/gu, " ").replace(ARTICLES, " ").replace(/\s+/g, " ").trim() + " ";
const variants = (s) => s.split("/").map((v) => words(v.replace(/\(.*?\)/g, ""))).filter((v) => v.trim().length >= 3);
const arVariants = (s) => s.split("/").map((v) => " " + v.replace(/[؟?]/g, "").trim() + " ").filter((v) => v.trim().length >= 3);

const INDEX = [
  ...DENTAL.map((t) => ({ keys: variants(t.fr), label: t.fr, pl: t.pl })),
  ...DARIJA.map((t) => ({ keys: [...variants(t.dj).filter((v) => v.trim().length >= 4), ...arVariants(t.ar)], label: `${t.dj} (\u2068${t.ar}\u2069)`, pl: t.pl })),
].filter((t) => t.keys.length);

/** Glossary entries whose French / Darija form appears in `text`. */
export function findTerms(text) {
  const hay = words(text);
  const seen = new Set();
  const out = [];
  for (const t of INDEX) {
    if (seen.has(t.label)) continue;
    if (t.keys.some((k) => hay.includes(k))) {
      seen.add(t.label);
      out.push({ term: t.label, pl: t.pl });
    }
  }
  return out;
}
